# author: greyshell
# description: travis pipeline for unittest, afl-fuzzing and cppcheck

language: c

jobs:
  exclude:
    - env: TEST_LIB=dumb_example
  include:
    - env: TEST_LIB=stack_singly_linkedlist_int

before_install:
 - echo "before install phase"

install:
 - sudo apt-get update
 - sudo apt-get install cppcheck less  -y
 - sudo .travis/install_afl.sh
 - sudo .travis/install_unity.sh

before_script:
 - echo "before_script phase"

script:
 - make test TEST_LIB=${TEST_LIB}; script/upload_unittest_report.sh
 - make fuzz TEST_LIB=${TEST_LIB}> /dev/null; script/upload_crash_report.sh

after_success:
 - script/notify_success.sh

after_failure:
 - script/notify_failure.sh

after script:
 - make cppcheck TEST_LIB=${TEST_LIB}; script/upload_cppcheck_report.sh
 - make clean-all

notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    rooms:
      - secure: ${SLACK_SECURE_TOKEN}
    on_success: always
    on_failure: always
