language: c

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install cppcheck -y
  - sudo .travis/install_afl.sh

script:
  - cd test/test_dumb_example/
  - make test

after_script:
  - cd test/test_dumb_example/
  - make cppcheck && cat build/results/cppcheck_results.txt
  - make fuzz && ls build/fuzz/out/crashes/id*

notifications:
  email:
    on_success: change
    on_failure: always