# author: greyshell
# description: travis pipeline for unittests, afl-fuzzing and cppcheck

language: c

jobs:
  include:
    - env: TEST_LIB=stack_singly_linkedlist_int
    - env: TEST_LIB=queue_singly_linkedlist_int
    - env: TEST_LIB=binary_heap_dynamic_array_int
    - env: TEST_LIB=sort

before_install:
  - skip

install:
  - sudo apt-get update
  - sudo apt-get install cppcheck less  -y
  - sudo .travis/install_afl.sh
  - sudo .travis/install_unity.sh

before_script:
  - .travis/notify_build_info.sh

script:
  - make test TEST_LIB=${TEST_LIB}; .travis/upload_unittest_report.sh
  - make fuzz TEST_LIB=${TEST_LIB} FUZZ_TIME=10s > /dev/null; .travis/upload_crash_report.sh

after_success:
  - .travis/notify_success.sh

after_failure:
  - .travis/notify_failure.sh

after script:
  - make cppcheck TEST_LIB=${TEST_LIB}; .travis/upload_cppcheck_report.sh
  - make clean-all

notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    rooms:
      - secure: bJXAZ2TpgDjPuMu7MvHocI64I6ta3zI/2zEifNvOdKr+rHlydessjuvoxqQWz+aCOZeuAALK47xukoHIfJVfs445xlp1MxoZICzjJjubsd6jHioSwJlExPJMsieBoZEBZtBnARApd1NNCiYrgHYCu+klKFCp9KuGMDTxNssePrSggNcQJLXbt2amgHoyzpKhbXZqgXex5BZdBCw4N8xE79Q8mU5YcuP4JYFA/vydz5J+CLNL0h3DooTrNy3HYL+3a37CFe/B2l0rSbGMsFmQpsdOMF9f5Pf6qrg+245LDoVbZ8Y9/zlFaISGM6y+g6XMP+Q1hEdVCjDclkx3/sCVX+vn2DIO7qR6KSLg3vH43dGtE0ckrO9O8+A0l4iCKvl1VAd9PYHBgwOaqgHn9/13KO1sCzGXHJ51RGxs5bjsTvd1rqn9oaJNy+HKU8NpX/X7rEN6Nf4ivqyryfgftTzxUYL1/tZ8+jHQJ+XFlpZc2+8dX/gkQGdoHUobHD39mjRAo17qcupbFOXt6fGnXn9FL6IfIi9X2s6GJJRqGtrPdPpqeSSWs2PnNQqQHZeYvoUxMaeuGEPdewmxY7/5fPVwTcKYWQ81eqTOo0vEN2jZ+y6BiEqjh9RvwoJSTChBCi3wcTowxbyq2ClbzCrRSgnhaleMGl2XDgjpr/TzJyurzmw=
    on_success: always
    on_failure: always
