site_name: libO2
nav:
  - General:
    - Quickstart: index.md
    - Supported libraries: supported_libraries.md
  - Guideline:
      - How to run unittest: guideline_unittest.md
      - How to fuzz: guideline_fuzz.md
      - Static code analysis: guideline_sca.md

theme:
  name: readthedocs
